all:
	g++ -Wall -save-temps -g -o  ./PHARMACIE_VANDERKINDER_ROLLING.exe ./PHARMACIE_VANDERKINDER_ROLLING.cpp

clean:
	rm PHARMACIE_VANDERKINDER_ROLLING.exe
	rm PHARMACIE_VANDERKINDER_ROLLING.ii
	rm PHARMACIE_VANDERKINDER_ROLLING.s
	rm PHARMACIE_VANDERKINDER_ROLLING.o
